name: CI-CD Demo

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo-site:${{ github.sha }} .

      - name: Run container (test env)
        run: docker run -d -p 8081:80 --name webtest demo-site:${{ github.sha }}

      - name: Smoke tests
        run: |
          chmod +x tests/smoke.sh
          ./tests/smoke.sh http://localhost:8081

      - name: Show logs (aide en cas d'échec)
        if: always()
        run: docker logs webtest || true

      - name: Copy static site for deploy
        if: always()
        run: docker cp webtest:/usr/share/nginx/html ./site

      - name: Clean up
        if: always()
        run: |
          docker stop webtest || true
          docker rm webtest || true
